spring:
  output:
    ansi:
      enabled: always
  application:
    name: webflux-coroutine
  r2dbc:
    url: r2dbc:pool:mariadb://192.168.0.45:3306/sample
    username: user
    password: 1234
logging:
  level:
    dev.example: debug

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:db-init/schema.sql

